default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  pool: 25
  database: <%= ENV['DB_NAME_DEV'] || 'flexcrow-dev' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] || 'flexcrow-test' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'flexcrow' %>